### ISSUE TITLE
add stale-while-revalidate directive

### ISSUE THREAD

**Issue by delgado3d** [tusbar/cache-control#71]
Although not part of the core HTTP caching standard, there is already good browser support
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility

`immutable` is also part of this which is already supported by this module.

More info at MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by tusbar** [comment]
Hey @delgado3d – would you mind creating a PR for this? I won’t have the time to work on this this week.

**Comment by delgado3d** [comment]
Sure, I'll give it a go.

**Comment by tusbar** [comment]
Released as [v0.4.0](https://github.com/tusbar/cache-control/releases/tag/v0.4.0) – thank you for your contribution. 🎉
